import {
  UserType,
  RoomType,
  ProductType,
  MovieType,
  SeatType,
  ShowtimeType,
  EmployeeType,
  ReviewType,
  CinemaType,
  TicketType,
  OrderType,
  PaymentType,
  OrderProductType,
  DiscountType,
} from "./interfaces/types";
import SmallPopImg from "./assets/images/examples/smallpop.svg";
import LargePopImg from "./assets/images/examples/bigpop.svg";
import CokeImg from "./assets/images/examples/coke.svg";
import LaysImg from "./assets/images/examples/lays.svg";
import WaterImg from "./assets/images/examples/water.svg";
import SpriteImg from "./assets/images/examples/sprite.svg";
import Combo1Img from "./assets/images/examples/combo1.svg";
import Combo2Img from "./assets/images/examples/combo2.svg";
import avatarMovieImg from "./assets/images/examples/avatarMovie.svg";
import jokerMovieImg from "./assets/images/examples/jokerMovie.svg";
import endgameMovieImg from "./assets/images/examples/endgameMovie.svg";
import screamMovieImg from "./assets/images/examples/screamMovie.svg";
import titanicMovieImg from "./assets/images/examples/titanicMovie.svg";
import barbieMovieImg from "./assets/images/examples/barbieMovie.svg";
import batmanMovieImg from "./assets/images/examples/batmanMovie.svg";
import shangchiMovieImg from "./assets/images/examples/shangchiMovie.svg";
import notimeMovieImg from "./assets/images/examples/notimeMovie.svg";
import venomMovieImg from "./assets/images/examples/venom.svg";

export const exampleProducts: ProductType[] = [
  {
    _id: "1",
    image: SmallPopImg,
    name: "Small Popcorn 20Oz",
    price: 5.0,
    category: "Food and Drinks",
  },
  {
    _id: "2",
    image: LargePopImg,
    name: "Large Popcorn 35Oz",
    price: 10.0,
    category: "Food and Drinks",
  },
  {
    _id: "3",
    image: CokeImg,
    name: "Coke 20Oz",
    price: 5.0,
    category: "Souvenirs",
  },
  {
    _id: "4",
    image: LaysImg,
    name: "Lays 30Oz",
    price: 3.0,
    category: "Food and Drinks",
  },
  {
    _id: "5",
    image: WaterImg,
    name: "Water 20Oz",
    price: 2.0,
    category: "Souvenirs",
  },
  {
    _id: "6",
    image: SpriteImg,
    name: "Sprite 20Oz",
    price: 5.0,
    category: "Souvenirs",
  },
  {
    _id: "7",
    image: Combo1Img,
    name: "Combo 1",
    price: 15.0,
    category: "Combo",
  },
  {
    _id: "8",
    image: Combo2Img,
    name: "Combo 2",
    price: 20.0,
    category: "Combo",
  },
  {
    _id: "9",
    image: SmallPopImg,
    name: "Small Popcorn 20Oz",
    price: 5.0,
    category: "Food and Drinks",
  },
  {
    _id: "10",
    image: LargePopImg,
    name: "Large Popcorn 35Oz",
    price: 10.0,
    category: "Food and Drinks",
  },
  {
    _id: "11",
    image: CokeImg,
    name: "Coke 20Oz",
    price: 5.0,
    category: "Souvenirs",
  },
  {
    _id: "12",
    image: LaysImg,
    name: "Lays 30Oz",
    price: 3.0,
    category: "Food and Drinks",
  },
  {
    _id: "13",
    image: WaterImg,
    name: "Water 20Oz",
    price: 2.0,
    category: "Souvenirs",
  },
  {
    _id: "14",
    image: SpriteImg,
    name: "Sprite 20Oz",
    price: 5.0,
    category: "Souvenirs",
  },
  {
    _id: "15",
    image: Combo1Img,
    name: "Combo 1",
    price: 15.0,
    category: "Combo",
  },
  {
    _id: "16",
    image: Combo2Img,
    name: "Combo 2",
    price: 20.0,
    category: "Combo",
  },
];

export const exampleMovies: MovieType[] = [
  {
    _id: "1",
    status: "Unknown",
    title: "Venom: The Last Dance",
    poster_url: venomMovieImg,
    genre: ["Action"],
    duration: 152, // Converted "2h 32m" to minutes
    country: "US",
    age_limit: 16,
    release_date: "2008-07-18",
    director: "Christopher Nolan",
    actors: [
      "Christian Bale",
      "Heath Ledger",
      "Aaron Eckhart",
      "Maggie Gyllenhaal",
      "Gary Oldman",
      "Michael Caine",
      "Morgan Freeman",
    ],
    description:
      "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    rating: 9.0,
    trailer_url: "https://youtu.be/o-3XPcvInmE?si=ljJ6N2AnQleV0YYU",
  },
  {
    _id: "2",
    status: "Now Playing",
    title: "Avengers: Endgame",
    poster_url: endgameMovieImg,
    genre: ["Action"],
    duration: 250,
    country: "US",
    age_limit: 13,
    release_date: "2019-04-26",
    director: "Anthony Russo, Joe Russo",
    actors: [
      "Robert Downey Jr",
      "Chris Evans",
      "Mark Ruffalo",
      "Chris Hemsworth",
      "Scarlett Johansson",
      "Jeremy Renner",
      "Don Cheadle",
    ],
    description:
      "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
    rating: 8.4,
    trailer_url: "https://youtu.be/TcMBFSGVi1c",
  },
  {
    _id: "3",
    status: "Coming Soon",
    title: "Scream",
    poster_url: screamMovieImg,
    genre: ["Horror"],
    duration: 111, // Converted "1h 51m" to minutes
    country: "US",
    age_limit: 18,
    release_date: "2022-01-14",
    director: "Matt Bettinelli-Olpin, Tyler Gillett",
    actors: [
      "Neve Campbell",
      "Courteney Cox",
      "David Arquette",
      "Melissa Barrera",
      "Jenna Ortega",
      "Jack Quaid",
      "Dylan Minnette",
    ],
    description:
      "Twenty-five years after a streak of brutal murders shocked the quiet town of Woodsboro, a new killer dons the Ghostface mask and begins targeting a group of teenagers to resurrect secrets from the town's deadly past.",
    rating: 7.2,
    trailer_url: "https://youtu.be/beToTslH17s",
  },
  {
    _id: "4",
    status: "Stopped",
    title: "Titanic",
    poster_url: titanicMovieImg,
    genre: ["Romance"],
    duration: 194, // Converted "3h 14m" to minutes
    country: "US",
    age_limit: 13,
    release_date: "1997-12-19",
    director: "James Cameron",
    actors: [
      "Leonardo DiCaprio",
      "Kate Winslet",
      "Billy Zane",
      "Kathy Bates",
      "Frances Fisher",
      "Danny Nucci",
      "Bill Paxton",
    ],
    description:
      "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
    rating: 7.8,
    trailer_url: "https://youtu.be/kVrqfYjkTdQ",
  },
  {
    _id: "5",
    status: "Coming Soon",
    title: "Barbie",
    poster_url: barbieMovieImg,
    genre: ["Comedy"],
    duration: 114, // Converted "1h 54m" to minutes
    country: "US",
    age_limit: 0,
    release_date: "2023-07-21",
    director: "Greta Gerwig",
    actors: [
      "Margot Robbie",
      "Ryan Gosling",
      "Will Ferrell",
      "Simu Liu",
      "America Ferrera",
      "Kate McKinnon",
      "Michael Cera",
    ],
    description:
      "A doll living in 'Barbieland' is expelled for not being perfect enough and sets off on an adventure in the real world.",
    rating: 7.5,
    trailer_url: "https://youtu.be/pBk4NYhWNMM",
  },
  {
    _id: "6",
    status: "Now Playing",
    title: "Batman",
    poster_url: batmanMovieImg,
    genre: ["Action"],
    duration: 200,
    country: "US",
    age_limit: 13,
    release_date: "2022-03-04",
    director: "Matt Reeves",
    actors: [
      "Robert Pattinson",
      "Zoë Kravitz",
      "Jeffrey Wright",
      "Colin Farrell",
      "Paul Dano",
      "John Turturro",
      "Andy Serkis",
    ],
    description:
      "When the Riddler, a sadistic serial killer, begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
    rating: 8.0,
    trailer_url: "https://youtu.be/mqqft2x_Aa4",
  },
  {
    _id: "7",
    status: "Now Playing",
    title: "Shang-Chi: The Legend of the Ten Rings",
    poster_url: shangchiMovieImg,
    genre: ["Action"],
    duration: 200,
    country: "US",
    age_limit: 13,
    release_date: "2021-09-03",
    director: "Destin Daniel Cretton",
    actors: [
      "Simu Liu",
      "Awkwafina",
      "Tony Chiu-Wai Leung",
      "Michelle Yeoh",
      "Fala Chen",
      "Meng'er Zhang",
      "Florian Munteanu",
    ],
    description:
      "Shang-Chi, the master of weaponry-based Kung Fu, is forced to confront his past after being drawn into the Ten Rings organization.",
    rating: 7.9,
    trailer_url: "https://youtu.be/8YjFbMbfXaQ",
  },
  {
    _id: "8",
    status: "Now Playing",
    title: "No Time To Die",
    poster_url: notimeMovieImg,
    genre: ["Action"],
    duration: 250,
    country: "UK",
    age_limit: 13,
    release_date: "2021-10-08",
    director: "Cary Joji Fukunaga",
    actors: [
      "Daniel Craig",
      "Rami Malek",
      "Léa Seydoux",
      "Lashana Lynch",
      "Ben Whishaw",
      "Naomie Harris",
      "Jeffrey Wright",
    ],
    description:
      "James Bond has left active service. His peace is short-lived when Felix Leiter, an old friend from the CIA, turns up asking for help, leading Bond onto the trail of a mysterious villain armed with dangerous new technology.",
    rating: 7.3,
    trailer_url: "https://youtu.be/BIhNsAtPbPI",
  },
  {
    _id: "9",
    status: "Now Playing",
    title: "Joker",
    poster_url: jokerMovieImg,
    genre: ["Drama"],
    duration: 122, // Converted "2h 2m" to minutes
    country: "US",
    age_limit: 18,
    release_date: "2019-10-04",
    director: "Todd Phillips",
    actors: [
      "Joaquin Phoenix",
      "Robert De Niro",
      "Zazie Beetz",
      "Frances Conroy",
      "Brett Cullen",
      "Shea Whigham",
      "Bill Camp",
    ],
    description:
      "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker.",
    rating: 8.5,
    trailer_url: "https://youtu.be/t433PEQGErc",
  },
  {
    _id: "10",
    status: "Coming Soon",
    title: "Avatar",
    poster_url: avatarMovieImg,
    genre: ["Sci-Fi"],
    duration: 210,
    country: "US",
    age_limit: 13,
    release_date: "2009-12-18",
    director: "James Cameron",
    actors: [
      "Sam Worthington",
      "Zoe Saldana",
      "Sigourney Weaver",
      "Stephen Lang",
      "Michelle Rodriguez",
      "Giovanni Ribisi",
      "Joel David Moore",
    ],
    description:
      "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
    rating: 7.8,
    trailer_url: "https://youtu.be/5PSNL1qE6VY",
  },
];

export const exampleSeats: SeatType[] = [
  // Left block: 2 columns
  { room_id: "1", _id: "1", seat_name: "A01", seat_column: -6 },
  { room_id: "1", _id: "2", seat_name: "A02", seat_column: -5 },
  { room_id: "1", _id: "3", seat_name: "B01", seat_column: -6 },
  { room_id: "1", _id: "4", seat_name: "B02", seat_column: -5 },
  { room_id: "1", _id: "5", seat_name: "C01", seat_column: -6 },
  { room_id: "1", _id: "6", seat_name: "C02", seat_column: -5 },
  { room_id: "1", _id: "7", seat_name: "D01", seat_column: -6 },
  { room_id: "1", _id: "8", seat_name: "D02", seat_column: -5 },
  { room_id: "1", _id: "9", seat_name: "E01", seat_column: -6 },
  { room_id: "1", _id: "10", seat_name: "E02", seat_column: -5 },
  { room_id: "1", _id: "11", seat_name: "F01", seat_column: -6 },
  { room_id: "1", _id: "12", seat_name: "F02", seat_column: -5 },
  { room_id: "1", _id: "13", seat_name: "G01", seat_column: -6 },
  { room_id: "1", _id: "14", seat_name: "G02", seat_column: -5 },
  { room_id: "1", _id: "15", seat_name: "H01", seat_column: -6 },
  { room_id: "1", _id: "16", seat_name: "H02", seat_column: -5 },
  { room_id: "1", _id: "17", seat_name: "I01", seat_column: -6 },
  { room_id: "1", _id: "18", seat_name: "I02", seat_column: -5 },
  { room_id: "1", _id: "19", seat_name: "J01", seat_column: -6 },
  { room_id: "1", _id: "20", seat_name: "J02", seat_column: -5 },
  { room_id: "1", _id: "21", seat_name: "K01", seat_column: -6 },
  { room_id: "1", _id: "22", seat_name: "K02", seat_column: -5 },
  { room_id: "1", _id: "23", seat_name: "L01", seat_column: -6 },
  { room_id: "1", _id: "24", seat_name: "L02", seat_column: -5 },

  // Right block: 8 columns
  { room_id: "1", _id: "25", seat_name: "A03", seat_column: -2 },
  { room_id: "1", _id: "26", seat_name: "A04", seat_column: -1 },
  { room_id: "1", _id: "27", seat_name: "A05", seat_column: 0 },
  { room_id: "1", _id: "28", seat_name: "A06", seat_column: 1 },
  { room_id: "1", _id: "29", seat_name: "A07", seat_column: 2 },
  { room_id: "1", _id: "30", seat_name: "A08", seat_column: 3 },
  { room_id: "1", _id: "31", seat_name: "A09", seat_column: 4 },
  { room_id: "1", _id: "32", seat_name: "A10", seat_column: 5 },

  { room_id: "1", _id: "33", seat_name: "B03", seat_column: -2 },
  { room_id: "1", _id: "34", seat_name: "B04", seat_column: -1 },
  { room_id: "1", _id: "35", seat_name: "B05", seat_column: 0 },
  { room_id: "1", _id: "36", seat_name: "B06", seat_column: 1 },
  { room_id: "1", _id: "37", seat_name: "B07", seat_column: 2 },
  { room_id: "1", _id: "38", seat_name: "B08", seat_column: 3 },
  { room_id: "1", _id: "39", seat_name: "B09", seat_column: 4 },
  { room_id: "1", _id: "40", seat_name: "B10", seat_column: 5 },

  { room_id: "1", _id: "41", seat_name: "C03", seat_column: -2 },
  { room_id: "1", _id: "42", seat_name: "C04", seat_column: -1 },
  { room_id: "1", _id: "43", seat_name: "C05", seat_column: 0 },
  { room_id: "1", _id: "44", seat_name: "C06", seat_column: 1 },
  { room_id: "1", _id: "45", seat_name: "C07", seat_column: 2 },
  { room_id: "1", _id: "46", seat_name: "C08", seat_column: 3 },
  { room_id: "1", _id: "47", seat_name: "C09", seat_column: 4 },
  { room_id: "1", _id: "48", seat_name: "C10", seat_column: 5 },

  { room_id: "1", _id: "49", seat_name: "D03", seat_column: -2 },
  { room_id: "1", _id: "50", seat_name: "D04", seat_column: -1 },
  { room_id: "1", _id: "51", seat_name: "D05", seat_column: 0 },
  { room_id: "1", _id: "52", seat_name: "D06", seat_column: 1 },
  { room_id: "1", _id: "53", seat_name: "D07", seat_column: 2 },
  { room_id: "1", _id: "54", seat_name: "D08", seat_column: 3 },
  { room_id: "1", _id: "55", seat_name: "D09", seat_column: 4 },
  { room_id: "1", _id: "56", seat_name: "D10", seat_column: 5 },

  { room_id: "1", _id: "57", seat_name: "E03", seat_column: -2 },
  { room_id: "1", _id: "58", seat_name: "E04", seat_column: -1 },
  { room_id: "1", _id: "59", seat_name: "E05", seat_column: 0 },
  { room_id: "1", _id: "60", seat_name: "E06", seat_column: 1 },
  { room_id: "1", _id: "61", seat_name: "E07", seat_column: 2 },
  { room_id: "1", _id: "62", seat_name: "E08", seat_column: 3 },
  { room_id: "1", _id: "63", seat_name: "E09", seat_column: 4 },
  { room_id: "1", _id: "64", seat_name: "E10", seat_column: 5 },

  { room_id: "1", _id: "65", seat_name: "F03", seat_column: -2 },
  { room_id: "1", _id: "66", seat_name: "F04", seat_column: -1 },
  { room_id: "1", _id: "67", seat_name: "F05", seat_column: 0 },
  { room_id: "1", _id: "68", seat_name: "F06", seat_column: 1 },
  { room_id: "1", _id: "69", seat_name: "F07", seat_column: 2 },
  { room_id: "1", _id: "70", seat_name: "F08", seat_column: 3 },
  { room_id: "1", _id: "71", seat_name: "F09", seat_column: 4 },
  { room_id: "1", _id: "72", seat_name: "F10", seat_column: 5 },

  { room_id: "1", _id: "73", seat_name: "G03", seat_column: -2 },
  { room_id: "1", _id: "74", seat_name: "G04", seat_column: -1 },
  { room_id: "1", _id: "75", seat_name: "G05", seat_column: 0 },
  { room_id: "1", _id: "76", seat_name: "G06", seat_column: 1 },
  { room_id: "1", _id: "77", seat_name: "G07", seat_column: 2 },
  { room_id: "1", _id: "78", seat_name: "G08", seat_column: 3 },
  { room_id: "1", _id: "79", seat_name: "G09", seat_column: 4 },
  { room_id: "1", _id: "80", seat_name: "G10", seat_column: 5 },

  { room_id: "1", _id: "81", seat_name: "H03", seat_column: -2 },
  { room_id: "1", _id: "82", seat_name: "H04", seat_column: -1 },
  { room_id: "1", _id: "83", seat_name: "H05", seat_column: 0 },
  { room_id: "1", _id: "84", seat_name: "H06", seat_column: 1 },
  { room_id: "1", _id: "85", seat_name: "H07", seat_column: 2 },
  { room_id: "1", _id: "86", seat_name: "H08", seat_column: 3 },
  { room_id: "1", _id: "87", seat_name: "H09", seat_column: 4 },
  { room_id: "1", _id: "88", seat_name: "H10", seat_column: 5 },

  { room_id: "1", _id: "89", seat_name: "I03", seat_column: -2 },
  { room_id: "1", _id: "90", seat_name: "I04", seat_column: -1 },
  { room_id: "1", _id: "91", seat_name: "I05", seat_column: 0 },
  { room_id: "1", _id: "92", seat_name: "I06", seat_column: 1 },
  { room_id: "1", _id: "93", seat_name: "I07", seat_column: 2 },
  { room_id: "1", _id: "94", seat_name: "I08", seat_column: 3 },
  { room_id: "1", _id: "95", seat_name: "I09", seat_column: 4 },
  { room_id: "1", _id: "96", seat_name: "I10", seat_column: 5 },

  { room_id: "1", _id: "97", seat_name: "J03", seat_column: -2 },
  { room_id: "1", _id: "98", seat_name: "J04", seat_column: -1 },
  { room_id: "1", _id: "99", seat_name: "J05", seat_column: 0 },
  { room_id: "1", _id: "100", seat_name: "J06", seat_column: 1 },
  { room_id: "1", _id: "101", seat_name: "J07", seat_column: 2 },
  { room_id: "1", _id: "102", seat_name: "J08", seat_column: 3 },
  { room_id: "1", _id: "103", seat_name: "J09", seat_column: 4 },
  { room_id: "1", _id: "104", seat_name: "J10", seat_column: 5 },

  { room_id: "1", _id: "105", seat_name: "K03", seat_column: -2 },
  { room_id: "1", _id: "106", seat_name: "K04", seat_column: -1 },
  { room_id: "1", _id: "107", seat_name: "K05", seat_column: 0 },
  { room_id: "1", _id: "108", seat_name: "K06", seat_column: 1 },
  { room_id: "1", _id: "109", seat_name: "K07", seat_column: 2 },
  { room_id: "1", _id: "110", seat_name: "K08", seat_column: 3 },
  { room_id: "1", _id: "111", seat_name: "K09", seat_column: 4 },
  { room_id: "1", _id: "112", seat_name: "K10", seat_column: 5 },

  { room_id: "1", _id: "113", seat_name: "L03", seat_column: -4 },
  { room_id: "1", _id: "114", seat_name: "L04", seat_column: -3 },
  { room_id: "1", _id: "115", seat_name: "L05", seat_column: -2 },
  { room_id: "1", _id: "116", seat_name: "L06", seat_column: -1 },
  { room_id: "1", _id: "117", seat_name: "L07", seat_column: 0 },
  { room_id: "1", _id: "118", seat_name: "L08", seat_column: 1 },
  { room_id: "1", _id: "119", seat_name: "L09", seat_column: 2 },
  { room_id: "1", _id: "120", seat_name: "L10", seat_column: 3 },
  { room_id: "1", _id: "121", seat_name: "L11", seat_column: 4 },
  { room_id: "1", _id: "122", seat_name: "L12", seat_column: 5 },
];

export const exampleShowtimes: ShowtimeType[] = [
  {
    _id: "1",
    room_id: "1",
    price: 12.99,
    movie_id: "1",
    showtime: "2025-4-23T10:00:00",
  },
  {
    _id: "2",
    room_id: "1",
    price: 12.99,
    movie_id: "2",
    showtime: "2025-4-23T13:00:00",
  },
  {
    _id: "3",
    room_id: "1",
    price: 12.99,
    movie_id: "3",
    showtime: "2025-4-23T16:20:00",
  },
  {
    _id: "4",
    room_id: "1",
    price: 12.99,
    movie_id: "4",
    showtime: "2025-4-23T19:30:00",
  },
  {
    _id: "5",
    room_id: "1",
    price: 12.99,
    movie_id: "5",
    showtime: "2025-4-23T22:00:00",
  },
  {
    _id: "6",
    room_id: "2",
    price: 12.99,
    movie_id: "6",
    showtime: "2025-4-22T10:00:00",
  },
  {
    _id: "7",
    room_id: "2",
    price: 12.99,
    movie_id: "7",
    showtime: "2025-4-22T13:00:00",
  },
  {
    _id: "8",
    room_id: "2",
    price: 12.99,
    movie_id: "8",
    showtime: "2025-4-22T16:20:00",
  },
  {
    _id: "9",
    room_id: "2",
    price: 12.99,
    movie_id: "9",
    showtime: "2025-4-22T19:30:00",
  },
  {
    _id: "10",
    room_id: "2",
    price: 12.99,
    movie_id: "1",
    showtime: "2025-4-22T22:00:00",
  },
  {
    _id: "11",
    room_id: "3",
    price: 12.99,
    movie_id: "1",
    showtime: "2025-4-23T10:00:00",
  },
  {
    _id: "12",
    room_id: "3",
    price: 12.99,
    movie_id: "2",
    showtime: "2025-4-23T13:00:00",
  },
  {
    _id: "13",
    room_id: "3",
    price: 12.99,
    movie_id: "3",
    showtime: "2025-4-23T16:20:00",
  },
  {
    _id: "14",
    room_id: "3",
    price: 12.99,
    movie_id: "4",
    showtime: "2025-4-23T19:30:00",
  },
  {
    _id: "15",
    room_id: "3",
    price: 12.99,
    movie_id: "5",
    showtime: "2025-4-23T22:00:00",
  },
  {
    _id: "16",
    room_id: "1",
    price: 12.99,
    movie_id: "6",
    showtime: "2025-4-23T11:00:00",
  },
  {
    _id: "17",
    room_id: "1",
    price: 12.99,
    movie_id: "7",
    showtime: "2025-4-23T12:00:00",
  },
  {
    _id: "18",
    room_id: "1",
    price: 12.99,
    movie_id: "8",
    showtime: "2025-4-23T13:00:00",
  },
  {
    _id: "19",
    room_id: "1",
    price: 12.99,
    movie_id: "9",
    showtime: "2025-4-23T14:00:00",
  },
  {
    _id: "20",
    room_id: "1",
    price: 12.99,
    movie_id: "1",
    showtime: "2025-4-23T15:00:00",
  },
  {
    _id: "21",
    room_id: "2",
    price: 12.99,
    movie_id: "1",
    showtime: "2025-4-23T16:00:00",
  },
  {
    _id: "22",
    room_id: "2",
    price: 12.99,
    movie_id: "2",
    showtime: "2025-4-23T17:00:00",
  },
  {
    _id: "23",
    room_id: "2",
    price: 12.99,
    movie_id: "3",
    showtime: "2025-4-23T18:00:00",
  },
  {
    _id: "24",
    room_id: "2",
    price: 12.99,
    movie_id: "4",
    showtime: "2025-4-23T19:00:00",
  },
  {
    _id: "25",
    room_id: "2",
    price: 12.99,
    movie_id: "5",
    showtime: "2025-4-23T20:00:00",
  },
  {
    _id: "26",
    room_id: "3",
    price: 12.99,
    movie_id: "6",
    showtime: "2025-4-23T21:00:00",
  },
  {
    _id: "27",
    room_id: "3",
    price: 12.99,
    movie_id: "7",
    showtime: "2025-4-24T22:00:00",
  },
  {
    _id: "28",
    room_id: "3",
    price: 12.99,
    movie_id: "8",
    showtime: "2025-4-24T23:00:00",
  },
  {
    _id: "29",
    room_id: "1",
    price: 12.99,
    movie_id: "9",
    showtime: "2025-4-24T11:00:00",
  },
  {
    _id: "30",
    room_id: "1",
    price: 12.99,
    movie_id: "1",
    showtime: "2025-4-22T12:00:00",
  },
  {
    _id: "31",
    room_id: "1",
    price: 12.99,
    movie_id: "1",
    showtime: "2025-4-22T13:00:00",
  },
  {
    _id: "32",
    room_id: "1",
    price: 12.99,
    movie_id: "2",
    showtime: "2025-4-22T14:00:00",
  },
  {
    _id: "33",
    room_id: "1",
    price: 12.99,
    movie_id: "3",
    showtime: "2025-4-22T15:00:00",
  },
  {
    _id: "34",
    room_id: "2",
    price: 12.99,
    movie_id: "4",
    showtime: "2025-4-22T16:00:00",
  },
  {
    _id: "35",
    room_id: "2",
    price: 12.99,
    movie_id: "5",
    showtime: "2025-4-22T17:00:00",
  },
  {
    _id: "36",
    room_id: "2",
    price: 12.99,
    movie_id: "6",
    showtime: "2025-4-22T18:00:00",
  },
  {
    _id: "37",
    room_id: "2",
    price: 12.99,
    movie_id: "7",
    showtime: "2025-4-22T19:00:00",
  },
  {
    _id: "38",
    room_id: "3",
    price: 12.99,
    movie_id: "8",
    showtime: "2025-4-22T20:00:00",
  },
  {
    _id: "39",
    room_id: "3",
    price: 12.99,
    movie_id: "9",
    showtime: "2025-4-22T21:00:00",
  },
  {
    _id: "40",
    room_id: "3",
    price: 12.99,
    movie_id: "1",
    showtime: "2025-4-22T22:00:00",
  },
  {
    _id: "41",
    room_id: "1",
    price: 12.99,
    movie_id: "1",
    showtime: "2025-4-22T23:00:00",
  },
  {
    _id: "42",
    room_id: "1",
    price: 12.99,
    movie_id: "2",
    showtime: "2025-4-23T11:00:00",
  },
  {
    _id: "43",
    room_id: "1",
    price: 12.99,
    movie_id: "3",
    showtime: "2025-4-23T12:00:00",
  },
  {
    _id: "44",
    room_id: "1",
    price: 12.99,
    movie_id: "4",
    showtime: "2025-4-23T13:00:00",
  },
  {
    _id: "45",
    room_id: "2",
    price: 12.99,
    movie_id: "5",
    showtime: "2025-4-23T14:00:00",
  },
  {
    _id: "46",
    room_id: "2",
    price: 12.99,
    movie_id: "6",
    showtime: "2025-4-23T15:00:00",
  },
  {
    _id: "47",
    room_id: "2",
    price: 12.99,
    movie_id: "7",
    showtime: "2025-4-23T16:00:00",
  },
  {
    _id: "48",
    room_id: "2",
    price: 12.99,
    movie_id: "8",
    showtime: "2025-4-23T17:00:00",
  },
  {
    _id: "49",
    room_id: "3",
    price: 12.99,
    movie_id: "9",
    showtime: "2025-4-23T18:00:00",
  },
  {
    _id: "50",
    room_id: "3",
    price: 12.99,
    movie_id: "1",
    showtime: "2025-4-23T19:00:00",
  },
  {
    _id: "51",
    room_id: "3",
    price: 12.99,
    movie_id: "1",
    showtime: "2025-4-23T20:00:00",
  },
  {
    _id: "52",
    room_id: "1",
    price: 12.99,
    movie_id: "2",
    showtime: "2025-4-23T21:00:00",
  },
  {
    _id: "53",
    room_id: "1",
    price: 12.99,
    movie_id: "3",
    showtime: "2025-4-23T22:00:00",
  },
  {
    _id: "54",
    room_id: "1",
    price: 12.99,
    movie_id: "4",
    showtime: "2025-4-23T23:00:00",
  },
  {
    _id: "55",
    room_id: "2",
    price: 12.99,
    movie_id: "5",
    showtime: "2025-4-23T09:00:00",
  },
  {
    _id: "56",
    room_id: "2",
    price: 12.99,
    movie_id: "6",
    showtime: "2025-4-23T10:00:00",
  },
  {
    _id: "57",
    room_id: "2",
    price: 12.99,
    movie_id: "7",
    showtime: "2025-4-23T11:00:00",
  },
  {
    _id: "58",
    room_id: "2",
    price: 12.99,
    movie_id: "8",
    showtime: "2025-4-23T12:00:00",
  },
  {
    _id: "59",
    room_id: "3",
    price: 12.99,
    movie_id: "9",
    showtime: "2025-4-23T13:00:00",
  },
  {
    _id: "60",
    room_id: "3",
    price: 12.99,
    movie_id: "1",
    showtime: "2025-4-23T14:00:00",
  },
  {
    _id: "61",
    room_id: "3",
    price: 12.99,
    movie_id: "1",
    showtime: "2025-4-23T15:00:00",
  },
  {
    _id: "62",
    room_id: "1",
    price: 12.99,
    movie_id: "2",
    showtime: "2025-4-23T16:00:00",
  },
  {
    _id: "63",
    room_id: "1",
    price: 12.99,
    movie_id: "3",
    showtime: "2025-4-23T17:00:00",
  },
  {
    _id: "64",
    room_id: "1",
    price: 12.99,
    movie_id: "4",
    showtime: "2025-4-23T18:00:00",
  },
  {
    _id: "65",
    room_id: "2",
    price: 12.99,
    movie_id: "5",
    showtime: "2025-4-23T19:00:00",
  },
  {
    _id: "66",
    room_id: "2",
    price: 12.99,
    movie_id: "6",
    showtime: "2025-4-23T20:00:00",
  },
  {
    _id: "67",
    room_id: "2",
    price: 12.99,
    movie_id: "7",
    showtime: "2025-4-23T21:00:00",
  },
  {
    _id: "68",
    room_id: "3",
    price: 12.99,
    movie_id: "8",
    showtime: "2025-4-23T22:00:00",
  },
  {
    _id: "69",
    room_id: "3",
    price: 12.99,
    movie_id: "9",
    showtime: "2025-4-23T23:00:00",
  },
  {
    _id: "70",
    room_id: "1",
    price: 12.99,
    movie_id: "1",
    showtime: "2025-4-22T09:00:00",
  },
  {
    _id: "71",
    room_id: "1",
    price: 12.99,
    movie_id: "1",
    showtime: "2025-4-22T10:00:00",
  },
  {
    _id: "72",
    room_id: "1",
    price: 12.99,
    movie_id: "2",
    showtime: "2025-4-22T11:00:00",
  },
  {
    _id: "73",
    room_id: "2",
    price: 12.99,
    movie_id: "3",
    showtime: "2025-4-22T12:00:00",
  },
  {
    _id: "74",
    room_id: "2",
    price: 12.99,
    movie_id: "4",
    showtime: "2025-4-22T13:00:00",
  },
  {
    _id: "75",
    room_id: "2",
    price: 12.99,
    movie_id: "5",
    showtime: "2025-4-22T14:00:00",
  },
  {
    _id: "76",
    room_id: "3",
    price: 12.99,
    movie_id: "6",
    showtime: "2025-4-22T15:00:00",
  },
  {
    _id: "77",
    room_id: "3",
    price: 12.99,
    movie_id: "7",
    showtime: "2025-4-22T16:00:00",
  },
  {
    _id: "78",
    room_id: "3",
    price: 12.99,
    movie_id: "8",
    showtime: "2025-4-22T17:00:00",
  },
  {
    _id: "79",
    room_id: "1",
    price: 12.99,
    movie_id: "9",
    showtime: "2025-4-22T18:00:00",
  },
  {
    _id: "80",
    room_id: "1",
    price: 12.99,
    movie_id: "1",
    showtime: "2025-4-22T19:00:00",
  },
  {
    _id: "81",
    room_id: "1",
    price: 12.99,
    movie_id: "1",
    showtime: "2025-4-22T20:00:00",
  },
  {
    _id: "82",
    room_id: "2",
    price: 12.99,
    movie_id: "2",
    showtime: "2025-4-22T21:00:00",
  },
  {
    _id: "83",
    room_id: "2",
    price: 12.99,
    movie_id: "3",
    showtime: "2025-4-22T22:00:00",
  },
  {
    _id: "84",
    room_id: "2",
    price: 12.99,
    movie_id: "4",
    showtime: "2025-4-22T23:00:00",
  },
  {
    _id: "85",
    room_id: "3",
    price: 12.99,
    movie_id: "5",
    showtime: "2025-4-23T09:00:00",
  },
  {
    _id: "86",
    room_id: "3",
    price: 12.99,
    movie_id: "6",
    showtime: "2025-4-23T10:00:00",
  },
  {
    _id: "87",
    room_id: "3",
    price: 12.99,
    movie_id: "7",
    showtime: "2025-4-23T11:00:00",
  },
  {
    _id: "88",
    room_id: "1",
    price: 12.99,
    movie_id: "8",
    showtime: "2025-4-23T12:00:00",
  },
  {
    _id: "89",
    room_id: "1",
    price: 12.99,
    movie_id: "9",
    showtime: "2025-4-23T13:00:00",
  },
  {
    _id: "90",
    room_id: "1",
    price: 12.99,
    movie_id: "1",
    showtime: "2025-4-23T14:00:00",
  },
  {
    _id: "91",
    room_id: "2",
    price: 12.99,
    movie_id: "1",
    showtime: "2025-4-23T15:00:00",
  },
  {
    _id: "92",
    room_id: "2",
    price: 12.99,
    movie_id: "2",
    showtime: "2025-4-23T16:00:00",
  },
  {
    _id: "93",
    room_id: "2",
    price: 12.99,
    movie_id: "3",
    showtime: "2025-4-23T17:00:00",
  },
  {
    _id: "94",
    room_id: "3",
    price: 12.99,
    movie_id: "4",
    showtime: "2025-4-23T18:00:00",
  },
  {
    _id: "95",
    room_id: "3",
    price: 12.99,
    movie_id: "5",
    showtime: "2025-4-23T19:00:00",
  },
  {
    _id: "96",
    room_id: "3",
    price: 12.99,
    movie_id: "6",
    showtime: "2025-4-23T20:00:00",
  },
  {
    _id: "97",
    room_id: "1",
    price: 12.99,
    movie_id: "7",
    showtime: "2025-4-23T21:00:00",
  },
  {
    _id: "98",
    room_id: "1",
    price: 12.99,
    movie_id: "8",
    showtime: "2025-4-23T22:00:00",
  },
  {
    _id: "99",
    room_id: "1",
    price: 12.99,
    movie_id: "9",
    showtime: "2025-4-23T23:00:00",
  }
];

// export const" exampleSeats: SeatType[] = [
//   // Left block: 2 columns
//   { room_id: 1, seat_id: 1, seat_name: "A01", seat_column: -6 },
//   { room_id: 1, seat_id: 2, seat_name: "A02", seat_column: -5 },
//   { room_id: 1, seat_id: 3, seat_name: "B01", seat_column: -6 },
//   { room_id: 1, seat_id: 4, seat_name: "B02", seat_column: -5 },
//   { room_id: 1, seat_id: 5, seat_name: "C01", seat_column: -6 },
//   { room_id: 1, seat_id: 6, seat_name: "C02", seat_column: -5 },
//   { room_id: 1, seat_id: 7, seat_name: "D01", seat_column: -6 },
//   { room_id: 1, seat_id: 8, seat_name: "D02", seat_column: -5 },
//   { room_id: 1, seat_id: 9, seat_name: "E01", seat_column: -6 },
//   { room_id: 1, seat_id: 10, seat_name: "E02", seat_column: -5 },
//   { room_id: 1, seat_id: 11, seat_name: "F01", seat_column: -6 },
//   { room_id: 1, seat_id: 12, seat_name: "F02", seat_column: -5 },
//   { room_id: 1, seat_id: 13, seat_name: "G01", seat_column: -6 },
//   { room_id: 1, seat_id: 14, seat_name: "G02", seat_column: -5 },
//   { room_id: 1, seat_id: 15, seat_name: "H01", seat_column: -6 },
//   { room_id: 1, seat_id: 16, seat_name: "H02", seat_column: -5 },
//   { room_id: 1, seat_id: 17, seat_name: "I01", seat_column: -6 },
//   { room_id: 1, seat_id: 18, seat_name: "I02", seat_column: -5 },
//   { room_id: 1, seat_id: 19, seat_name: "J01", seat_column: -6 },
//   { room_id: 1, seat_id: 20, seat_name: "J02", seat_column: -5 },
//   { room_id: 1, seat_id: 21, seat_name: "K01", seat_column: -6 },
//   { room_id: 1, seat_id: 22, seat_name: "K02", seat_column: -5 },
//   { room_id: 1, seat_id: 23, seat_name: "L01", seat_column: -6 },
//   { room_id: 1, seat_id: 24, seat_name: "L02", seat_column: -5 },

//   // Right block: 8 columns
//   { room_id: 1, seat_id: 25, seat_name: "A03", seat_column: -2 },
//   { room_id: 1, seat_id: 26, seat_name: "A04", seat_column: -1 },
//   { room_id: 1, seat_id: 27, seat_name: "A05", seat_column: 0 },
//   { room_id: 1, seat_id: 28, seat_name: "A06", seat_column: 1 },
//   { room_id: 1, seat_id: 29, seat_name: "A07", seat_column: 2 },
//   { room_id: 1, seat_id: 30, seat_name: "A08", seat_column: 3 },
//   { room_id: 1, seat_id: 31, seat_name: "A09", seat_column: 4 },
//   { room_id: 1, seat_id: 32, seat_name: "A10", seat_column: 5 },

//   { room_id: 1, seat_id: 33, seat_name: "B03", seat_column: -2 },
//   { room_id: 1, seat_id: 34, seat_name: "B04", seat_column: -1 },
//   { room_id: 1, seat_id: 35, seat_name: "B05", seat_column: 0 },
//   { room_id: 1, seat_id: 36, seat_name: "B06", seat_column: 1 },
//   { room_id: 1, seat_id: 37, seat_name: "B07", seat_column: 2 },
//   { room_id: 1, seat_id: 38, seat_name: "B08", seat_column: 3 },
//   { room_id: 1, seat_id: 39, seat_name: "B09", seat_column: 4 },
//   { room_id: 1, seat_id: 40, seat_name: "B10", seat_column: 5 },

//   { room_id: 1, seat_id: 41, seat_name: "C03", seat_column: -2 },
//   { room_id: 1, seat_id: 42, seat_name: "C04", seat_column: -1 },
//   { room_id: 1, seat_id: 43, seat_name: "C05", seat_column: 0 },
//   { room_id: 1, seat_id: 44, seat_name: "C06", seat_column: 1 },
//   { room_id: 1, seat_id: 45, seat_name: "C07", seat_column: 2 },
//   { room_id: 1, seat_id: 46, seat_name: "C08", seat_column: 3 },
//   { room_id: 1, seat_id: 47, seat_name: "C09", seat_column: 4 },
//   { room_id: 1, seat_id: 48, seat_name: "C10", seat_column: 5 },

//   { room_id: 1, seat_id: 49, seat_name: "D03", seat_column: -2 },
//   { room_id: 1, seat_id: 50, seat_name: "D04", seat_column: -1 },
//   { room_id: 1, seat_id: 51, seat_name: "D05", seat_column: 0 },
//   { room_id: 1, seat_id: 52, seat_name: "D06", seat_column: 1 },
//   { room_id: 1, seat_id: 53, seat_name: "D07", seat_column: 2 },
//   { room_id: 1, seat_id: 54, seat_name: "D08", seat_column: 3 },
//   { room_id: 1, seat_id: 55, seat_name: "D09", seat_column: 4 },
//   { room_id: 1, seat_id: 56, seat_name: "D10", seat_column: 5 },

//   { room_id: 1, seat_id: 57, seat_name: "E03", seat_column: -2 },
//   { room_id: 1, seat_id: 58, seat_name: "E04", seat_column: -1 },
//   { room_id: 1, seat_id: 59, seat_name: "E05", seat_column: 0 },
//   { room_id: 1, seat_id: 60, seat_name: "E06", seat_column: 1 },
//   { room_id: 1, seat_id: 61, seat_name: "E07", seat_column: 2 },
//   { room_id: 1, seat_id: 62, seat_name: "E08", seat_column: 3 },
//   { room_id: 1, seat_id: 63, seat_name: "E09", seat_column: 4 },
//   { room_id: 1, seat_id: 64, seat_name: "E10", seat_column: 5 },

//   { room_id: 1, seat_id: 65, seat_name: "F03", seat_column: -2 },
//   { room_id: 1, seat_id: 66, seat_name: "F04", seat_column: -1 },
//   { room_id: 1, seat_id: 67, seat_name: "F05", seat_column: 0 },
//   { room_id: 1, seat_id: 68, seat_name: "F06", seat_column: 1 },
//   { room_id: 1, seat_id: 69, seat_name: "F07", seat_column: 2 },
//   { room_id: 1, seat_id: 70, seat_name: "F08", seat_column: 3 },
//   { room_id: 1, seat_id: 71, seat_name: "F09", seat_column: 4 },
//   { room_id: 1, seat_id: 72, seat_name: "F10", seat_column: 5 },

//   { room_id: 1, seat_id: 73, seat_name: "G03", seat_column: -2 },
//   { room_id: 1, seat_id: 74, seat_name: "G04", seat_column: -1 },
//   { room_id: 1, seat_id: 75, seat_name: "G05", seat_column: 0 },
//   { room_id: 1, seat_id: 76, seat_name: "G06", seat_column: 1 },
//   { room_id: 1, seat_id: 77, seat_name: "G07", seat_column: 2 },
//   { room_id: 1, seat_id: 78, seat_name: "G08", seat_column: 3 },
//   { room_id: 1, seat_id: 79, seat_name: "G09", seat_column: 4 },
//   { room_id: 1, seat_id: 80, seat_name: "G10", seat_column: 5 },

//   { room_id: 1, seat_id: 81, seat_name: "H03", seat_column: -2 },
//   { room_id: 1, seat_id: 82, seat_name: "H04", seat_column: -1 },
//   { room_id: 1, seat_id: 83, seat_name: "H05", seat_column: 0 },
//   { room_id: 1, seat_id: 84, seat_name: "H06", seat_column: 1 },
//   { room_id: 1, seat_id: 85, seat_name: "H07", seat_column: 2 },
//   { room_id: 1, seat_id: 86, seat_name: "H08", seat_column: 3 },
//   { room_id: 1, seat_id: 87, seat_name: "H09", seat_column: 4 },
//   { room_id: 1, seat_id: 88, seat_name: "H10", seat_column: 5 },

//   { room_id: 1, seat_id: 89, seat_name: "I03", seat_column: -2 },
//   { room_id: 1, seat_id: 90, seat_name: "I04", seat_column: -1 },
//   { room_id: 1, seat_id: 91, seat_name: "I05", seat_column: 0 },
//   { room_id: 1, seat_id: 92, seat_name: "I06", seat_column: 1 },
//   { room_id: 1, seat_id: 93, seat_name: "I07", seat_column: 2 },
//   { room_id: 1, seat_id: 94, seat_name: "I08", seat_column: 3 },
//   { room_id: 1, seat_id: 95, seat_name: "I09", seat_column: 4 },
//   { room_id: 1, seat_id: 96, seat_name: "I10", seat_column: 5 },

//   { room_id: 1, seat_id: 97, seat_name: "J03", seat_column: -2 },
//   { room_id: 1, seat_id: 98, seat_name: "J04", seat_column: -1 },
//   { room_id: 1, seat_id: 99, seat_name: "J05", seat_column: 0 },
//   { room_id: 1, seat_id: 100, seat_name: "J06", seat_column: 1 },
//   { room_id: 1, seat_id: 101, seat_name: "J07", seat_column: 2 },
//   { room_id: 1, seat_id: 102, seat_name: "J08", seat_column: 3 },
//   { room_id: 1, seat_id: 103, seat_name: "J09", seat_column: 4 },
//   { room_id: 1, seat_id: 104, seat_name: "J10", seat_column: 5 },

//   { room_id: 1, seat_id: 105, seat_name: "K03", seat_column: -2 },
//   { room_id: 1, seat_id: 106, seat_name: "K04", seat_column: -1 },
//   { room_id: 1, seat_id: 107, seat_name: "K05", seat_column: 0 },
//   { room_id: 1, seat_id: 108, seat_name: "K06", seat_column: 1 },
//   { room_id: 1, seat_id: 109, seat_name: "K07", seat_column: 2 },
//   { room_id: 1, seat_id: 110, seat_name: "K08", seat_column: 3 },
//   { room_id: 1, seat_id: 111, seat_name: "K09", seat_column: 4 },
//   { room_id: 1, seat_id: 112, seat_name: "K10", seat_column: 5 },

//   { room_id: 1, seat_id: 113, seat_name: "L03", seat_column: -4 },
//   { room_id: 1, seat_id: 114, seat_name: "L04", seat_column: -3 },
//   { room_id: 1, seat_id: 115, seat_name: "L05", seat_column: -2 },
//   { room_id: 1, seat_id: 116, seat_name: "L06", seat_column: -1 },
//   { room_id: 1, seat_id: 117, seat_name: "L07", seat_column: 0 },
//   { room_id: 1, seat_id: 118, seat_name: "L08", seat_column: 1 },
//   { room_id: 1, seat_id: 119, seat_name: "L09", seat_column: 2 },
//   { room_id: 1, seat_id: 120, seat_name: "L10", seat_column: 3 },
//   { room_id: 1, seat_id: 121, seat_name: "L11", seat_column: 4 },
//   { room_id: 1, seat_id: 122, seat_name: "L12", seat_column: 5 },
// ];

// export const exampleReviews: ReviewType[] = [
//   {
//     review_id: 1,
//     user_id: 1,
//     showtime_id: 1,
//    rating: 5,
//     comment: "Amazing movie! Highly recommend.",
//     created_at: "2025-4-23T10:00:00",
//   },
//   {
//     review_id: 2,
//     user_id: 2,
//     showtime_id: 2,
//    rating: 4,
//     comment: "Great movie, but a bit too long.",
//     created_at: "2025-4-23T13:00:00",
//   },
//   {
//     review_id: 3,
//     user_id: 3,
//     showtime_id: 3,
//    rating: 3,
//     comment: "It was okay, not the best.",
//     created_at: "2025-4-23T16:20:00",
//   },
//   {
//     review_id: 4,
//     user_id: 4,
//     showtime_id: 1,
//    rating: 2,
//     comment: "Not my type of movie.",
//     created_at: "2025-4-23T19:30:00",
//   },
//   {
//     review_id: 5,
//     user_id: 5,
//     showtime_id: 1,
//    rating: 1,
//     comment: "Terrible movie, waste of time.",
//     created_at: "2025-4-23T22:00:00",
//   },
//   {
//     review_id: 6,
//     user_id: 6,
//     showtime_id: 3,
//    rating: 5,
//     comment: "Loved every moment of it!",
//     created_at: "2025-4-22T10:00:00",
//   },
//   {
//     review_id: 7,
//     user_id: 7,
//     showtime_id: 2,
//    rating: 4,
//     comment: "Very entertaining.",
//     created_at: "2025-4-22T13:00:00",
//   },
//   {
//     review_id: 8,
//     user_id: 8,
//     showtime_id: 3,
//    rating: 3,
//     comment: "It was decent.",
//     created_at: "2025-4-22T16:20:00",
//   },
//   {
//     review_id: 9,
//     user_id: 9,
//     showtime_id: 9,
//     rating: 2,
//     comment: "Could have been better.",
//     created_at: "2025-4-22T19:30:00",
//   },
//   {
//     review_id: 10,
//     user_id: 10,
//     showtime_id: 10,
//     rating: 1,
//     comment: "Really bad experience.",
//     created_at: "2025-4-22T22:00:00",
//   },
//   {
//     review_id: 11,
//     user_id: 11,
//     showtime_id: 11,
//     rating: 5,
//     comment: "Fantastic movie!",
//     created_at: "2025-4-23T10:00:00",
//   },
//   {
//     review_id: 12,
//     user_id: 12,
//     showtime_id: 12,
//     rating: 4,
//     comment: "Really enjoyed it.",
//     created_at: "2025-4-23T13:00:00",
//   },
//   {
//     review_id: 13,
//     user_id: 13,
//     showtime_id: 13,
//     rating: 3,
//     comment: "It was alright.",
//     created_at: "2025-4-23T16:20:00",
//   },
//   {
//     review_id: 14,
//     user_id: 14,
//     showtime_id: 14,
//     rating: 2,
//     comment: "Not great.",
//     created_at: "2024-12-23T19:30:00",
//   },
//   {
//     review_id: 15,
//     user_id: 15,
//     showtime_id: 15,
//     rating: 1,
//     comment: "Would not recommend.",
//     created_at: "2024-12-23T22:00:00",
//   },
//   {
//     review_id: 16,
//     user_id: 16,
//     showtime_id: 16,
//     rating: 5,
//     comment: "Absolutely loved it!",
//     created_at: "2024-12-21T11:00:00",
//   },
//   {
//     review_id: 17,
//     user_id: 17,
//     showtime_id: 17,
//     rating: 4,
//     comment: "Very good movie.",
//     created_at: "2024-12-21T12:00:00",
//   },
//   {
//     review_id: 18,
//     user_id: 18,
//     showtime_id: 18,
//     rating: 3,
//     comment: "It was fine.",
//     created_at: "2024-12-21T13:00:00",
//   },
//   {
//     review_id: 19,
//     user_id: 19,
//     showtime_id: 19,
//     rating: 2,
//     comment: "Not my favorite.",
//     created_at: "2024-12-21T14:00:00",
//   },
//   {
//     review_id: 20,
//     user_id: 20,
//     showtime_id: 20,
//     rating: 1,
//     comment: "Really didn't like it.",
//     created_at: "2024-12-21T15:00:00",
//   },
// ];

// export const exampleTickets: TicketType[] = [
//   {
//     ticket_id: 1,
//     showtime_id: 1,
//     seat_id: "A1",
//     order_id: 1,
//   },
//   {
//     ticket_id: 1,
//     showtime_id: 1,
//     seat_id: "F1",
//     order_id: 1,
//   },
//   {
//     ticket_id: 2,
//     showtime_id: 2,
//     seat_id: "A2",
//     order_id: 2,
//   },
//   {
//     ticket_id: 3,
//     showtime_id: 3,
//     seat_id: "A3",
//     order_id: 3,
//   },
//   {
//     ticket_id: 4,
//     showtime_id: 4,
//     seat_id: "A4",
//     order_id: 4,
//   },
//   {
//     ticket_id: 5,
//     showtime_id: 5,
//     seat_id: "A5",
//     order_id: 5,
//   },
//   {
//     ticket_id: 6,
//     showtime_id: 1,
//     seat_id: "A1",
//     order_id: 1,
//   },
//   {
//     ticket_id: 7,
//     showtime_id: 1,
//     seat_id: "F1",
//     order_id: 1,
//   },
// ];

// export const exampleOrders: OrderType[] = [
//   {
//     order_id: 1,
//     user_id: 1,
//     total_price: 50.0,
//     status: "completed",
//     created_at: "2024-12-20T10:00:00",
//   },
//   {
//     order_id: 2,
//     user_id: 2,
//     total_price: 30.0,
//     status: "pending",
//     created_at: "2024-12-20T11:00:00",
//   },
//   {
//     order_id: 3,
//     user_id: 3,
//     total_price: 20.0,
//     status: "cancelled",
//     created_at: "2024-12-20T12:00:00",
//   },
//   {
//     order_id: 4,
//     user_id: 4,
//     total_price: 40.0,
//     status: "completed",
//     created_at: "2024-12-20T13:00:00",
//   },
//   {
//     order_id: 5,
//     user_id: 5,
//     total_price: 60.0,
//     status: "pending",
//     created_at: "2024-12-20T14:00:00",
//   },
// ];

// export const examplePayments: PaymentType[] = [
//   {
//     payment_id: 1,
//     order_id: 1,
//     amount: 50.0,
//     payment_method: "Credit Card",
//     status: "completed",
//     discount_id: 1,
//     paid_at: "2024-12-20T10:30:00",
//   },
//   {
//     payment_id: 2,
//     order_id: 2,
//     amount: 30.0,
//     payment_method: "PayPal",
//     status: "pending",
//     discount_id: 2,
//     paid_at: "2024-12-20T11:30:00",
//   },
//   {
//     payment_id: 3,
//     order_id: 3,
//     amount: 20.0,
//     payment_method: "Credit Card",
//     status: "cancelled",
//     discount_id: 3,
//     paid_at: "2024-12-20T12:30:00",
//   },
//   {
//     payment_id: 4,
//     order_id: 4,
//     amount: 40.0,
//     payment_method: "Debit Card",
//     status: "completed",
//     discount_id: 4,
//     paid_at: "2024-12-20T13:30:00",
//   },
//   {
//     payment_id: 5,
//     order_id: 5,
//     amount: 60.0,
//     payment_method: "Credit Card",
//     status: "pending",
//     discount_id: 5,
//     paid_at: "2024-12-20T14:30:00",
//   },
// ];

// export const exampleOrderProducts: OrderProductType[] = [
//   {
//     order_id: 1,
//     product_id: 1,
//     quantity: 2,
//   },
//   {
//     order_id: 2,
//     product_id: 2,
//     quantity: 1,
//   },
//   {
//     order_id: 3,
//     product_id: 3,
//     quantity: 3,
//   },
//   {
//     order_id: 4,
//     product_id: 4,
//     quantity: 1,
//   },
//   {
//     order_id: 5,
//     product_id: 5,
//     quantity: 2,
//   },
// ];

// export const exampleDiscounts: DiscountType[] = [
//   {
//     discount_id: 1,
//     code: "DISCOUNT10",
//     discount_type: "percentage",
//     value: 10,
//     min_purchase: 50,
//     expiry_date: "2024-12-31",
//   },
//   {
//     discount_id: 2,
//     code: "DISCOUNT20",
//     discount_type: "fixed",
//     value: 20,
//     min_purchase: 100,
//     expiry_date: "2024-12-31",
//   },
//   {
//     discount_id: 3,
//     code: "DISCOUNT30",
//     discount_type: "percentage",
//     value: 30,
//     min_purchase: 150,
//     expiry_date: "2024-12-31",
//   },
//   {
//     discount_id: 4,
//     code: "DISCOUNT40",
//     discount_type: "fixed",
//     value: 40,
//     min_purchase: 200,
//     expiry_date: "2024-12-31",
//   },
//   {
//     discount_id: 5,
//     code: "DISCOUNT50",
//     discount_type: "percentage",
//     value: 50,
//     min_purchase: 250,
//     expiry_date: "2024-12-31",
//   },
// ];
